DEVOPS-9385: Lambda function alertToTicket updated to reflect environ…
dandb/pd2jira_python pull request #2
Opened 2017-07-24 22:49 UTC by mprince

…ment

2017-07-25 19:54 UTC, taoistmath requested changes

2017-07-25 19:54 UTC, taoistmath commented on pd2jira_python/Ticket.py
> +    PD_SERVICES_FILTER = {
this needs to be in config.yml somehow

2017-07-25 19:54 UTC, taoistmath commented on pd2jira_python/Ticket.py
> +                self.update_config_with_filter(self.PD_SERVICES_FILTER,custom_fields['customfield_10930'],self.service_name)
this needs to be in config.yml somehow

2017-07-26 21:48 UTC, mprince commented
To test the code I have created the lambda function manually in the dev account. Below is the results of a ticket created with the environment being set `DEV` as it is the first word of the `subject_sumary`
![aws lambda test success](https://user-images.githubusercontent.com/5485148/28645200-7d770b48-7211-11e7-9e37-ea93c95aa60f.png)
![aws lambda test configuration](https://user-images.githubusercontent.com/5485148/28645202-7d7e12ee-7211-11e7-8b3c-00c498f1eb14.png)
![devops-9470 successfully created with correct env](https://user-images.githubusercontent.com/5485148/28645201-7d7a77ba-7211-11e7-8f86-e9bc2dcb6a32.png)

2017-07-26 21:56 UTC, ishwinder-singh approved these changes

2017-07-26 23:00 UTC, mayn approved these changes

2017-07-26 23:04 UTC, taoistmath approved these changes

2017-07-27 00:02 UTC, merged